// data.js
export const scientists = [
  {
    id: 0,
    name: "Alan Turing",
    birthYear: 1912,
    university: "Cambridge",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/8Km9tLL.jpg",
  },
  {
    id: 1,
    name: "Albert Einstein",
    birthYear: 1879,
    university: "Zurich",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/S6L6v6b.jpg",
  },
  {
    id: 2,
    name: "John Nash",
    birthYear: 1928,
    university: "Princeton",
    hasNobel: true,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/MK3eW3A.jpg",
  },
  {
    id: 3,
    name: "Milton Friedman",
    birthYear: 1912,
    university: "Columbia",
    hasNobel: true,
    profession: "economist",
    imageUrl: "https://i.imgur.com/7vQD0fP.jpg",
  },
  {
    id: 4,
    name: "Marie Curie",
    birthYear: 1867,
    university: "Sorbonne",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/yXOvdOS.jpg",
  },
  {
    id: 5,
    name: "Isaac Newton",
    birthYear: 1643,
    university: "Cambridge",
    hasNobel: false,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/lICfvbD.jpg",
  },
  {
    id: 6,
    name: "Ada Lovelace",
    birthYear: 1815,
    university: "London",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/QIrZWGI.jpg",
  },
  {
    id: 7,
    name: "Richard Feynman",
    birthYear: 1918,
    university: "Princeton",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/jA8hHMpm.jpg",
  },
  {
    id: 8,
    name: "John von Neumann",
    birthYear: 1903,
    university: "Budapest",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/T093VpAm.jpg",
  },
  {
    id: 9,
    name: "Friedrich Hayek",
    birthYear: 1899,
    university: "Vienna",
    hasNobel: true,
    profession: "economist",
    imageUrl: "https://i.imgur.com/7vQD0fP.jpg",
  },
  {
    id: 10,
    name: "Stephen Hawking",
    birthYear: 1942,
    university: "Oxford",
    hasNobel: false,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/MK3eW3As.jpg",
  },
  {
    id: 11,
    name: "Katherine Johnson",
    birthYear: 1918,
    university: "West Virginia",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/MK3eW3A.jpg",
  },
  {
    id: 12,
    name: "Paul Samuelson",
    birthYear: 1915,
    university: "Harvard",
    hasNobel: true,
    profession: "economist",
    imageUrl: "https://i.imgur.com/yXOvdOS.jpg",
  },
  {
    id: 13,
    name: "Niels Bohr",
    birthYear: 1885,
    university: "Copenhagen",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/8Km9tLL.jpg",
  },
  {
    id: 14,
    name: "Euclides",
    birthYear: -325,
    university: "Alexandria",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/lICfvbD.jpg",
  },
  {
    id: 15,
    name: "Amartya Sen",
    birthYear: 1933,
    university: "Cambridge",
    hasNobel: true,
    profession: "economist",
    imageUrl: "https://i.imgur.com/QIrZWGI.jpg",
  },
  {
    id: 16,
    name: "Werner Heisenberg",
    birthYear: 1901,
    university: "Munich",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/S6L6v6b.jpg",
  },
  {
    id: 17,
    name: "Kurt Gödel",
    birthYear: 1906,
    university: "Vienna",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/jA8hHMpm.jpg",
  },
  {
    id: 18,
    name: "Adam Smith",
    birthYear: 1723,
    university: "Glasgow",
    hasNobel: false,
    profession: "economist",
    imageUrl: "https://i.imgur.com/T093VpAm.jpg",
  },
  {
    id: 19,
    name: "Max Planck",
    birthYear: 1858,
    university: "Munich",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/MK3eW3As.jpg",
  },
  {
    id: 20,
    name: "Emmy Noether",
    birthYear: 1882,
    university: "Erlangen",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/yXOvdOS.jpg",
  },
  {
    id: 21,
    name: "John Maynard Keynes",
    birthYear: 1883,
    university: "Cambridge",
    hasNobel: false,
    profession: "economist",
    imageUrl: "https://i.imgur.com/8Km9tLL.jpg",
  },
  {
    id: 22,
    name: "Enrico Fermi",
    birthYear: 1901,
    university: "Pisa",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/S6L6v6b.jpg",
  },
  {
    id: 23,
    name: "Bernhard Riemann",
    birthYear: 1826,
    university: "Göttingen",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/lICfvbD.jpg",
  },
  {
    id: 24,
    name: "Joseph Stiglitz",
    birthYear: 1943,
    university: "MIT",
    hasNobel: true,
    profession: "economist",
    imageUrl: "https://i.imgur.com/QIrZWGI.jpg",
  },
  {
    id: 25,
    name: "Erwin Schrödinger",
    birthYear: 1887,
    university: "Vienna",
    hasNobel: true,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/jA8hHMpm.jpg",
  },
  {
    id: 26,
    name: "Carl Friedrich Gauss",
    birthYear: 1777,
    university: "Helmstedt",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/T093VpAm.jpg",
  },
  {
    id: 27,
    name: "Elinor Ostrom",
    birthYear: 1933,
    university: "UCLA",
    hasNobel: true,
    profession: "economist",
    imageUrl: "https://i.imgur.com/MK3eW3As.jpg",
  },
  {
    id: 28,
    name: "Michael Faraday",
    birthYear: 1791,
    university: "Royal Institution",
    hasNobel: false,
    profession: "physicist",
    imageUrl: "https://i.imgur.com/MK3eW3A.jpg",
  },
  {
    id: 29,
    name: "Sofia Kovalevskaya",
    birthYear: 1850,
    university: "Göttingen",
    hasNobel: false,
    profession: "mathematician",
    imageUrl: "https://i.imgur.com/yXOvdOS.jpg",
  },
];
